apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentbit-daemonset
  namespace: {{ .Release.Name }}-ns
  labels:
    k8s-app: {{ .Release.Name }}
    app: {{ .Release.Name }}
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
 selector:
   matchLabels:
     name: {{ .Release.Name }}
 template:
   metadata:
     labels:
       name: {{ .Release.Name }}
       app: {{ .Release.Name }}
       version: v1
       kubernetes.io/cluster-service: "true"
   spec:
     serviceAccount: {{ .Release.Name }}-account
     serviceAccountName: {{ .Release.Name }}-account
     tolerations:
     - key: node-role.kubernetes.io/master
       effect: NoSchedule
     containers:
     - name: {{ .Release.Name }}
       image: {{ .Values.image.name }}:{{ .Values.image.tag }}
       imagePullPolicy: {{ .Values.image.pullPolicy }}
       ports:
         - containerPort: 2020 
       volumeMounts:
       - name: varlog
         mountPath: /var/log
       - name: varlogcontainers
         mountPath: /var/log/containers
       - name: varlibdockercontainers
         mountPath: /var/lib/docker/containers
         readOnly: true
       - name: fluent-bit-config
         mountPath: /fluent-bit/etc/
     volumes:
     - name: varlog
       hostPath:
         path: /var/log
     - name: varlogcontainers
       hostPath:
         path: /var/log/containers
     - name: varlibdockercontainers
       hostPath:
         path: /var/lib/docker/containers
     - name: fluent-bit-config
       configMap:
         name: {{ .Release.Name }}-configmap
